name: Integers

on:
  - pull_request
  - push
  - workflow_dispatch

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          # the ocaml fork doesn't work easily on windows and macOS
          # - windows-latest
          # - macos-latest
        ocaml-compiler:
          - ocaml-variants.4.02.1+modular-implicits
          - ocaml-variants.4.02.1+modular-implicits-ber

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
          opam-repositories: |
            default: https://github.com/ocaml/opam-repository.git
            modular-implicits: https://github.com/modular-implicits/modular-implicits-opam.git

      - run: opam install . --deps-only --with-test

      - run: opam exec -- dune build

      - run: opam exec -- dune runtest
