name: Integers

on:
  - pull_request
  - push
  - workflow_dispatch

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          # OCaml 4.02 doesn't work easily on ARM macOS
          # - macos-latest
        ocaml-compiler:
          - ocaml-variants.4.02.1+modular-implicits
          - ocaml-variants.4.02.1+modular-implicits-ber

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}

      - run: opam install . --deps-only --with-test

      - run: opam exec -- dune build

      - run: opam exec -- dune runtest
